version: '2'

services:
  twitter_egosearch:
    image: senyoltw/twitter_egosearch
    restart: always
    environment:
      - keyword=せにょ|セニョ|ワタナベ書店|お前が神を殺したいなら
      - webhook_url=https://maker.ifttt.com/trigger/{event}/with/key/{secret key}
      - twitter_consumer_key=XXXXXXX
      - twitter_consumer_secret=XXXXXXX
      - twitter_access_token_key=XXXXXXX
      - twitter_access_token_secret=XXXXXXX
